version: '3.8'

services:
  store-api:
    image: store-api:latest
    ports:
      - "8080:8080"
    environment:
      # Stripe
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}

      # Database
      - DATABASE_HOST=${DATABASE_HOST:-mysql}
      - DATABASE_PORT=${DATABASE_PORT:-3306}
      - DATABASE_NAME=${DATABASE_NAME:-eazystore}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

      # JWT
      - JWT_SECRET=${JWT_SECRET}

      # Email
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

    # Charger depuis fichier .env
    env_file:
      - .env

    depends_on:
      - mysql

    networks:
      - store-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - store-network

volumes:
  mysql-data:

networks:
  store-network:
    driver: bridge